### PR TITLE
Fixed IDL.

### PR DESCRIPTION
**Pull request by bkaradzic**
Generated code when dropped into bgfx builds! Yey! :+1:

### CODE REVIEW

**Comment by bkaradzic** [comment]
Actually never mind I did something that made it appear to work. It's not working yet...

**Comment by bkaradzic** [comment]
Ok, now it builds.

typedef struct encoder_s encoder_t is required, I'll just fix that in header, no need for IDL to mess with it.

But function names with 2D, and 3D in name strip D out of it.

**Comment by cloudwu** [comment]
It's hard to split words by one pattern, because type name and func name use different camlcase.

So I convert func name to upper camlcase first, ant then we can use the pattern `"[%u%d]+%l*"` (number is considered as upper) . This can solve the name like `createTexture2D` .

**Comment by bkaradzic** [comment]
It works! :+1: :)

**Pull request merged**
